#!/bin/bash -ue
CREDS_FILE="${CREDS_FILE:-"creds.env"}"
[ -f "$CREDS_FILE" ] && source "$CREDS_FILE"
[ -n "$PRIVADO_USERNAME" ] || { echo >&2 "ERROR: PRIVADO_USERNAME not set or missing creds file; exit 255; }
[ -n "$PRIVADO_PASSWORD" ] || { echo >&2 "ERROR: PRIVADO_PASSWORD not set or missing creds file; exit 255; }
API_KEY="${API_KEY:-"9f994c466340e8f2ed60a99396fecb6a"}"
CLIENT_API_URL="${CLIENT_API_URL:-"https://client-api.privado.io/v1"}"
PRIVADO_DATA_DIR="${PRIVADO_DATA_DIR:-"data"}"
LOGIN_TOKEN_FILE="${LOGIN_TOKEN:-"$PRIVADO_DATA_DIR/token.json"}"
USER_AGENT="${USER_AGENT:-"App: 3.0.0 (576942783), macOS: Version 12.4 (Build 21F79)"}"

command -v curl >/dev/null 2>&1 || { echo >&2 "I require curl but it's not installed.  Aborting."; exit 254; }
command -v jq >/dev/null 2>&1 || { echo >&2 "I require jq but it's not installed.  Aborting."; exit 254; }

[ -f "$LOGIN_TOKEN_FILE" ] || { echo >&2 "ERROR: not logged in"; exit 100; }
AUTH_TOKEN="$(cat "$LOGIN_TOKEN_FILE" | jq -r '.access_token')"
[ -n "$AUTH_TOKEN" ] || { echo >&2 "ERROR: no auth access_token found, login again"; exit 101; }

curl "$CLIENT_API_URL/get_customer_data/" \
--compressed --silent \
-X POST \
-H "User-Agent: $USER_AGENT" \
-H "Authorization: Bearer $AUTH_TOKEN" \
-H 'Content-Type: application/json' \
-d '{
  "username" : "'$PRIVADO_USERNAME'",
  "api_key" : "'$API_KEY'"
}' | jq '.data'
